[general]
import = ["./themes/flow.toml"]

[window]
opacity = 0.97
decorations = "none"
blur = false
dynamic_padding = true
title = "Alacritty"
dynamic_title = true
# Windowed , Maximized , Fullscreen
startup_mode = "Windowed"

[window.padding]
x = 10
y = 10

[font]
size = 15

[font.normal]
family = "AdwaitaMono Nerd Font Mono"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.bold_italic]
style = "Bold Italic"

# [font.offset]
# x = 0
# y = 4

[cursor.style]
blinking = "On"
shape = "Block"

[scrolling]
history = 20000
multiplier = 3

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[env]
TERM = "xterm-256color"
